# Generated by Django 4.0.6 on 2022-07-11 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_baby', models.BooleanField(default=False)),
                ('external_id', models.IntegerField()),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.specie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evolution_type', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('external_id', models.IntegerField()),
                ('evolution_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evolutions.evolutionchain')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.specie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
