# Generated by Django 4.0.6 on 2022-07-10 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('species', '0001_initial'),
        ('evolutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolution',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolution_specie', to='species.specie'),
        ),
    ]
