# Generated by Django 4.0.6 on 2022-07-10 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evolutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10)),
                ('external_id', models.IntegerField()),
                ('evolution_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolution_chain', to='evolutions.evolutionchain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
