# Generated by Django 4.0.6 on 2022-07-10 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=15)),
                ('weight', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('external_id', models.IntegerField()),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.specie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PokemonStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_stat', models.IntegerField()),
                ('effort', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='pokemons.pokemon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
